[package]
name = "netadmin_server"
version = "0.1.0"
edition = "2021"
authors = ["Georgiy Korneev <kgeorgiy@kgeorgiy.info>"]
description = "NetAdmin server"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
